project:
  type: website
  output-dir: docs

language: 
      search-text-placeholder: Search

website:
  title: Unified Virtual Assistant
  favicon: images/bee.png
  page-navigation: true
  search: 
    type: overlay
  navbar:
    pinned: true
    logo: images/IBMlogo.png
    right: 
      - icon: github
        href: https://github.com/ibm-client-engineering/unified-virtual-assistant
      - icon: linkedin
        menu:
          - text: Share on your LinkedIn
            href:  https://www.linkedin.com/company/ibm/
          - text:  IBM LinkedIn
            href:  https://www.linkedin.com/company/ibm/
  sidebar:
    - title: "Contents"
      style: docked
      collapse-level: 1
      search: false
      contents:
        - href: index.qmd
          text: Problem Definition
        - section: Solution Overview
          contents:
            - text: Prepare
              href: prepare.qmd
            - text: Environment
              href: environment.qmd
        - section: Implementation Methodology
          contents:
            - text: User Interface
              href: ./Implementation/imp-UI.qmd
            - text: Generative-AI Driven Routing
              href: ./Implementation/imp-genai-rout.qmd
            - section: RAG Document Search
              contents:
                - text: watsonx Discovery
                  href: ./Implementation/watsonx-dis.qmd
                - text: watson Discovery
                  href: ./Implementation/watson-dis.qmd
            - section: Governance
              contents:
                - text: watsonx Governance
                  href: ./Implementation/watsonx-gov.qmd
                - text: RAG Attribution Links
                  href: ./Implementation/rag-attr-links.qmd
            - section: Third-Party Applications
              contents:
                - text: ServiceNow
                  href: ./Implementation/imp-snow.qmd
                - text: Workday
                  href: ./Implementation/imp-workday.qmd
                - text: Genesys
                  href: ./Implementation/imp-genesys.qmd
            - section: Identity and Access Management
              contents:
                - text: IBM Security Verify
                  href: ./Implementation/imp-verify-assis.qmd
                - text: Simulation
                  href: ./Implementation/imp-sim.qmd
        - text: Key Takeaways
          href: key-takeaway.qmd

  page-footer: 
    background: black
    left: 
        <div class ="listitem"><a href="https://ibm.com" rel="noopener noreferrer" class="footerLogo"><img src="https://www.ibm.com/brand/experience-guides/developer/8f4e3cc2b5d52354a6d43c8edba1e3c9/02_8-bar-reverse.svg" alt="IBM Logo" class="footer__logo themedComponent_node_modules-@docusaurus-theme-common-lib-components-ThemedComponent-styles-module themedComponent--light_node_modules-@docusaurus-theme-common-lib-components-ThemedComponent-styles-module" width="250" height="250"></a></div> 
format:
  html:
    theme: custom.scss
    toc: true
    toc-location: right



