
---
title: "Unified Virtual Assistant"
subtitle: "Leverage watsonx Orchestrate to build a unified user experiance with gen-AI routing, IAM, governance, RAG, and third-party integrations."
author: Eashan Thakuria, John Scott
format: html
---

---
Description: "Leverage watsonx Orchestrate to build a unified user experiance with gen-AI routing, IAM, governance, RAG, and third-party integrations."
---
## Overview

### Business Statement
- Siloed internal chatbots are disrupting enterprise operations, compliance, and architectural standards.
- Employees are frustrated because they have to locate the right chatbot to answer their specific questions.
- Enterprise Architecture team is frustrated because lines of business will launch their own chatbot to fill their teams’ specific needs.
- Compliance teams are frustrated because there is no single point of oversight to ensures that chatbot responses are grounded on vetted information and that sensitive material remains protected. ​

### Challenges
- **User Experience challenges:**
    - **Time to information:** Information is difficult to find in a timely manner, as employees need to first know which chatbot to leverage for their particular question.
    - **Limited Access:** users will only be able to leverage the chatbots they are aware of. Many employees will be without the conversational search of a chatbot unless they have awareness and access to it.
    - **Limited capabilities and integration**: very few chatbots are currently designed to do more than provide information. Employees need to take extra steps in order to action on the insight (like opening tickets, connecting with support, etc)
- **Cost and Operational challenges:**
    - **Redundant efforts:** lines of business across the business are duplicating efforts by creating redundant chatbots.
    - **Scalability:** Without a unified approach, every new chatbot that is added only magnifies the existing user experience challenges and info risk challenges.
- **Information Challenges:**
    - **Veracity Risk:** How can Enterprise Architecture and Compliance teams ensure that the many chatbots across each line of business are providing employees information grounded on vetted source material?
    - **Security and Sensitivity Risk:** How can Enterprise Architecture and Compliance teams ensure that sensitive material remains protected across specified clearance levels?
- **Enterprise-level governance:** Enterprise Architecture lacks a single view of all LLMs deployed in the organization.

### Desired Outcomes
- A platform that can unite across lines of business
- Flexibility to connect with existing systems as well as extend to future additions.
- Enable users to take actions (like opening tickets, changing passwords, etc)
- Enable users to answer questions, grounded on pre-approved source material
- Governed access to sensitive content (only allow access to content that you are cleared for)
- Delegate specified questions to vetted chatbots that may already exist across the enterprise

### Expected Benefits to the business
- A More Informed Workforce: less noise per inquiry, less time to answers
- Cost and Operational Efficiency Gains: reduced duplicated efforts and a scalable framework
- Enhanced Compliance and Governance: a united framework enables clearer centralized oversight - including models deployed, model health, source information, governed access to sensitive material

## Solution Description

To build a unified virtual assistant and achieve the desired outcomes for success, this solution will leverage <span style="color:#2c62f5;">x</span> Orchestrate to deliver:

* **Identity and Access Management (IAM):**
    * Secure Login: Authenticates users based on roles.
    * Access Control: Restricts actions to authorized data and features.
    * Role-Based Privileges:
        * Admins: Access advanced features like global password changes.
        * Users: Limited to basic functions, ensuring simplicity and security.

* **Generative AI-Driven Routing:** Classifies user prompts into categories, improving conversation routing accuracy and streamlining interactions.
* **RAG Document Search:** Ensures accurate, reliable search results by combining a Data Repository, Vector Database, and Large Language Model, with up-to-date information and source links.
* **Third-Party Integrations:** Connects the chatbot to platforms like ServiceNow to automate workflows, reduce silos, and enable customized, efficient operations.
* **Governance:** Implements IBM® watson<span style="color:#2c62f5;">x</span>.governance™ to manage AI risks, ensure compliance, monitor models, and document processes, fostering transparency and accountability.
* **Subordinate Bot Mediation:** Enables seamless collaboration with existing chatbots by delegating domain-specific requests while providing unified responses through the parent bot.









