---
title: "Software Requirements"
format: html
---

## **Web-chat Interface**
- *watson<span style="color:#2c62f5;">x</span> Orchestrate*
    - Dedicated WxO Tenant with Admin access
- *IBM Cloud Object Storage*: Lite Plan

## **Document Search**
For RAG Document  Search you can leverage two different methods:
<ol>
<li>watson<span style="color:#2c62f5;">x</span> Discovery
<li>watson Discovery
</ol>

### watson<span style="color:#2c62f5;">x</span> Discovery
- *watson<span style="color:#2c62f5;">x</span> Discovery*: Platinum Plan (Probably need more than 16GB of RAM)
- *watson<span style="color:#2c62f5;">x</span>.ai*
    - *Watson Machine Learning*: Standard Plan
    - *watson<span style="color:#2c62f5;">x</span> Studio*: Lite Plan
- *IBM Cloud Object Storage*: Lite Plan

### Watson Discovery
- *watson Discovery*: Plus Plan
- *watson<span style="color:#2c62f5;">x</span>.ai*
    - *Watson Machine Learning*: Standard Plan
    - *watson<span style="color:#2c62f5;">x</span> Studio*: Lite Plan

## **Governance**
- *watson<span style="color:#2c62f5;">x</span>.ai*
    - *Watson Machine Learning*: Standard Plan
- *watson<span style="color:#2c62f5;">x</span>.governance*: Essentials Plan

## **Third Party Applications**

### ServiceNow
- ServiceNow developer account

### Workday
- Workday Application

### Genesys
- Genesys Cloud CX Account

## **Identity and Access Management**
- *IBM Security Verify*